# Generated by Django 3.0.5 on 2020-04-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200424_1214'),
        ('todo', '0002_auto_20200131_0131'),
    ]

    operations = [
    ]
